-- Fix passwords with correct BCrypt hash
-- Hash generated by the application: $2a$10$8WCBs9/Pp95vdIkKGqzFeeywGsNEEGdMNYHge7/QPUrFnm5fGgQx6

UPDATE user 
SET password = '$2a$10$8WCBs9/Pp95vdIkKGqzFeeywGsNEEGdMNYHge7/QPUrFnm5fGgQx6';

SELECT email, password FROM user LIMIT 3;
